# This is a configuration file for golangci-lint.
# https://golangci-lint.run/usage/configuration/

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 